---
abstract: 'Syntactic sugar for GET+POST handlers'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Dancer::Test: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Syntax-GetPost
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dancer::Plugin::Syntax::GetPost:
    file: lib/Dancer/Plugin/Syntax/GetPost.pm
    version: 0.001
requires:
  Dancer: 0
  Dancer::Plugin: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/dancer-plugin-syntax-getpost/issues
  homepage: https://metacpan.org/release/Dancer-Plugin-Syntax-GetPost
  repository: git://github.com/dagolden/dancer-plugin-syntax-getpost.git
version: 0.001
